config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'activities#index'

  resources :activities do
    collection do
      get :download_csv
    end
  end

  scope module: :api, defaults: {format: :json}, path: "api" do
    scope module: :v1, constraints: Constraints::ApiConstraint.new(version: 1, default: true) do
    end
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  DEFAULT_DECORATOR = ActivityDecorator

  ACTIVITY_TYPES = [
    "PublicMeetup",
    "SpeechDraft",
    "InternalMeetup",
    "ConferenceSpeech",
    "Hackathon"
  ].freeze

  belongs_to :user

  validates_with ContractResolver

  DEFAULT_DECORATOR.instance_methods(false).each do |m|
    delegate(m, to: :decorated)
  end

  def decorated
    @decorated ||= DEFAULT_DECORATOR.new(self)
  end

  class << self
    # need for children policy lookup
    def policy_class
      ActivityPolicy
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conference_speech.rb
class ConferenceSpeech < Activity
end

app/models/hackathon.rb
class Hackathon < Activity
end

app/models/internal_meetup.rb
class InternalMeetup < Activity
end

app/models/public_meetup.rb
class PublicMeetup < Activity
end

app/models/speech_draft.rb
class SpeechDraft < Activity
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable, :recoverable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :activities

  validates :username, uniqueness: true
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  # GET /activities or /activities.json
  def index
    @activities = Activity.includes(:user).all
  end

  # GET /activities/1 or /activities/1.json
  def show
    @activity = Activity.find(params[:id])
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
    authorize!(activity)
  end

  # POST /activities or /activities.json
  def create
    @activity = current_user.activities.new(activity_params)

    respond_to do |format|
      if activity.save
        format.html { redirect_to activity_path(activity), notice: "Activity was successfully created." }
        format.json { render :show, status: :created, location: activity_path(activity) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    authorize!(activity)

    respond_to do |format|
      if activity.update(activity_params)
        format.html { redirect_to activity_path(activity), notice: "Activity was successfully updated." }
        format.json { render :show, status: :ok, location: activity_path(activity) }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    authorize!(activity)

    activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: "Activity was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def download_csv
    activities = Activity.includes(:user).order(:start_at).all

    result = Activities::GenerateCsv.call(activities)

    respond_to do |format|
      case result
      when Success
        format.csv { send_data(result.value!, filename: "activities.#{Time.zone.now.to_i}.csv") }
      when Failure
        format.json { render json: result.failure, status: :unprocessable_entity }
      end
    end
  end

  private

  def activity
    # todo: move to repository
    @activity ||= current_user.activities.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(*%i[title type short_description start_at end_at])
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::API
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Dry::Monads[:result]

  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!

  protected

  # todo: move to parametersanitizer
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [
      :username,
      :name,
      :middle_name,
      :last_name
    ])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_form.html.erb
<%= simple_form_for(activity, as: :activity, url: url) do |f| %>
  <%= f.input :title, autofocus: true %>
  <%= f.input :type, collection: activity.types, prompt: "Select activity type" %>
  <%= f.input :short_description, as: :text %>

  <%= f.input :start_at, as: :datetime, start_year: Time.zone.now.year %>
  <%= f.input :end_at, as: :datetime, start_year: Time.zone.now.year %>

  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
        <% activity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.button :submit, value: "Save", class: 'w-100 my-1 btn-primary' %>
<% end %>

app/views/activities/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Editing Activity</h1>

      <%= render 'form', activity: @activity, url: activity_path(@activity) %>

      <%= link_to 'Show', activity_path(@activity) %> |
      <%= link_to 'Back', activities_path %>
    </div>
  </div>
</div>

app/views/activities/index.html.erb
<h1>Activities</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Time</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.title %></td>
        <td><%= activity.author %></td>
        <!-- todo: move to presenter -->
        <td><%= activity.start_at.to_formatted_s(:long) %></td>
        <td>
          <%= link_to 'Show', activity_path(activity) %>
          <% if allowed_to?(:change?, activity) %>
            <%= link_to 'Edit', edit_activity_path(activity) %>
            <%= link_to 'Destroy', activity_path(activity), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %> |
<%= link_to 'Download as CSV', download_csv_activities_url(format: :csv) %>

app/views/activities/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>New Activity</h1>

      <%= render 'form', activity: @activity, url: activities_path %>

      <%= link_to 'Back', activities_path %>
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<div class="container">
  <div class="row">
    <div class="col d-flex flex-row justify-content-center">

      <% begin %>
        <%= render @activity %>
      <!-- I'm tottaly not sure that this is a good idea -->
      <% rescue ActionView::MissingTemplate %>
        <div class="card" style="width: 400px;">
          <div class="card-body">
            <h2 class="card-title text-center"><%= @activity.title %></h2>
            <p class="text-muted text-right">Author: <%= @activity.author %></p>
            <div class="card-text text-center"><%= @activity.short_description %></div>
          </div>
          <div class="card-footer text-right">
            <%= link_to 'Edit', edit_activity_path(@activity) %> |
            <%= link_to 'Back', activities_path %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/hackathons/_hackathon.html.erb
<div class="card" style="width: 400px;">
  <div class="card-body">
    <h2 class="card-title text-center"><%= @activity.title %></h2>
    <p class="text-muted text-right">Author: <%= @activity.author %></p>
    <div class="card-text text-center"><%= @activity.short_description %></div>
    <div class="card-text text-right">Duration: ~<%= @activity.duration_in_hours.round %>h</div>
  </div>
  <div class="card-footer text-right">
    <%= link_to 'Edit', edit_activity_path(@activity) %> |
    <%= link_to 'Back', activities_path %>
  </div>
</div>

app/views/internal_meetups/_internal_meetup.html.erb
<div class="card" style="width: 400px;">
  <div class="card-body">
    <h2 class="card-title text-center"><%= @activity.title %></h2>
    <p class="text-muted text-right">Author: <%= @activity.author %></p>
    <div class="card-text text-center"><%= @activity.short_description %></div>
  </div>
  <div class="card-footer text-right">
    <%= link_to 'Edit', edit_activity_path(@activity) %> |
    <%= link_to 'Back', activities_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetupsCalendar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="d-flex flex-column">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
        <div class="container">
          <a class="navbar-brand" href="#">Meetup Calendar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item <%= 'active' if current_page?(root_path) %>">
                <a class="nav-link" href="/">Home
                  <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item <%= 'active' if current_page?(activities_path) %>">
                <a class="nav-link" href="/activities">Activities</a>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, class: "nav-link", method: :delete %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container flex-fill">
      <div class="row">
        <div class="col">
          <% if notice.present? %>
            <div class="notice alert alert-primary"><%= notice %></div>
          <% end %>
          <% if alert.present? %>
            <div class="alert alert-danger"><%= alert %></div>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </main>

    <footer class="footer bg-dark">
      <div class="container text-center">
        <%= image_tag('evrone_sponsor.png') %>
        <div class="text-white">Copyright &copy; Evrone 2021</div>
      </div>
    </footer>
  </body>
</html>

app/views/speech_drafts/_speech_draft.html.erb
<div class="card" style="width: 400px;">
  <%= image_tag('evrone.jpg', class: 'card-img-top') %>
  <div class="card-body">
    <h2 class="card-title text-center"><%= @activity.title %></h2>
    <p class="text-muted text-right">Author: <%= @activity.author %></p>
    <div class="card-text text-center"><%= @activity.short_description %></div>
  </div>
  <div class="card-footer text-right">
    <%= link_to 'Edit', edit_activity_path(@activity) %> |
    <%= link_to 'Back', activities_path %>
  </div>
</div>